config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root "home#index"

  get "up" => "rails/health#show", as: :rails_health_check
  namespace :users do
    resources :profiles, only: [:show]
  end
  resources :home
  resources :tweets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet

  validates :body, presence: true, length: { minimum: 5, maximum: 200 }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet

  validates :user_id, uniqueness: { scope: :tweet_id }
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :origin, class_name: 'Tweet', optional: true
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :body, presence: true, length: { minimum: 1, maximum: 280 }, unless: :retweet?
  validates :body, length: { minimum: 1, maximum: 280 }, allow_blank: true

  scope :recent, -> { order(created_at: :desc) }
  def retweet?
    origin_id.present?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :validatable

  has_many :tweets, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :email, presence: true, uniqueness: true
  validates :username, presence: true,
            length: { minimum: 3, maximum: 50 },
            uniqueness: true,
            format: { with: /\A[a-zA-Z0-9_]+\z/ }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @tweets = collection

    if user_signed_in?
      @new_tweet = Tweet.new(user: current_user)
    end
  end

  private

  def collection
    Tweet.recent
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_user!, only: :destroy

  def show
    @tweet = resource
  end

  def new
    @tweet = Tweet.new(user: current_user)
  end

  def edit
    @tweet = resource

    respond_to :turbo_stream
  end

  def create
    @tweet = current_user.tweets.build(tweet_params)

    respond_to do |format|
      if @tweet.save
        flash[:notice] = 'Tweet was successfully created.'
      else
        flash.now[:error] = @tweet.errors.full_messages.join(", ")
      end

      format.turbo_stream
    end
  end

  def update
    @tweet = resource

    respond_to do |format|
      if @tweet.update(tweet_params)
        flash.now[:notice] = "Tweet was successfully updated."
      else
        flash.now[:error] = @tweet.errors.full_messages.join(", ")
      end

      format.turbo_stream
    end
  end

  def destroy
    @tweet = resource

    respond_to do |format|
      if @tweet.destroy
        flash.now[:notice] = "Tweet was successfully destroyed."
      else
        flash.now[:error] = @tweet.errors.full_messages.join(", ")
      end

      format.turbo_stream
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(:body, :user_id, :origin_id)
  end

  def collection
    Tweet.includes(:user).recent
  end

  def resource
    collection.find(params[:id])
  end

  def authorize_user!
    @tweet = current_user.tweets.find(params[:id])
  end
end

app/controllers/users/profiles_controller.rb
class Users::ProfilesController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = resource
    @tweets = collection
  end

  private

  def resource
    User.find(params[:id])
  end

  def collection
    resource.tweets.recent
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
   before_action :configure_sign_up_params, only: [:create]
   def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_classes(type)
    case type
    when 'notice'
      'notice'
    when 'alert'
      'alert'
    else
      'tweet-error'
    end
  end
end

app/views/home/index.html.erb
<% content_for :header_title do %>
  For you
<% end %>
<%= render 'tweets/partials/form', tweet: @new_tweet %>

<%= turbo_stream_from 'tweets' %>
<div id="tweets">
  <%= render partial: 'tweets/tweet', collection: @tweets %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="bg-black text-gray-200">
  <%= turbo_frame_tag "modal" %>
    <main class="container mx-auto px-5">
      <%= render "shared/flash_messages" %>
      <div class="flex justify-center">
        <div class="relative min-h-screen">
          <%= render "shared/left_sidebar" %>
        </div>
        <div class="w-2/5 mr-32 border-x border-color min-h-screen">
          <%= render "shared/header" %>
          <%= yield %>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
    <div class="flash-position <%= flash_classes(type) %>" role="alert" data-controller="flash">
      <p class="font-bold"><%= type.capitalize %></p>
      <p><%= message %></p>
    </div>
<% end %>

app/views/shared/_header.html.erb
<header id="header" class="header"><h2><%= yield(:header_title) || 'Twitter' %></h2></header>
<div id="flash_messages">
  <%= render 'shared/flash_messages', tweet: @tweet %>
</div>

app/views/shared/_left_sidebar.html.erb
<aside id="sidebar" class="sticky top-0 mr-28">
  <nav>
    <ul class="space-y-4 grid justify-items-start" data-controller="dropdown" data-dropdown-hidden-class="hidden">
      <li class="mb-3 main-li"><%= inline_svg('icon.svg', class: "h-10") %></li>
      <%= link_to root_path do %>
        <li class="main-li"><%= inline_svg('home.svg', class: "h-10") %><p>Home</p></li>
      <% end %>
      <% if user_signed_in? %>
        <li class="flex items-center main-li" data-action="click->dropdown#toggle">
          <%= inline_svg('user.svg', class: "h-10") %>
          <div>
            <p class="text-base">Profile</p>
            <p class="text-sm text-gray-500">@<%= current_user.username %></p>
          </div>
          <%= inline_svg('dots.svg', class: "h-7") %>
          <%= render "shared/dropdown/sidebar" %>
        </li>
      <% end %>
    </ul>
  </nav>
</aside>

app/views/shared/dropdown/_sidebar.html.erb
<ul id="dropdown" data-dropdown-target="dropdown" class="dropdown hidden">

  <%= link_to users_profile_path(current_user) do %>
    <li class="regular-li rounded-t-lg flex items-start">
      <span class="ml-2">Tweets</span>
    </li>
  <% end %>

  <%= link_to destroy_user_session_path, data: { turbo_method: :delete } do %>
    <li class="logout rounded-b-lg">
      <%= inline_svg('logout.svg', class: "h-4") %>
      <span class="ml-2">Log out</span>
    </li>
  <% end %>

</ul>

app/views/shared/dropdown/_tweet.html.erb
<ul id="dropdown" data-dropdown-target="dropdown" class="dropdown hidden">

  <%= link_to tweet_path(tweet), data: { turbo_method: :delete, turbo_stream: true, turbo_confirm: 'Are you sure?' }  do %>
    <li class="logout rounded-t-lg flex items-start">
      <%= inline_svg('trash.svg', class: "h-4") %>
      <span class="ml-2">Delete</span>
    </li>
  <% end %>

  <%= link_to edit_tweet_path(tweet), data: { turbo_frame: "modal", turbo_stream: true } do %>
    <li class="regular-li rounded-b-lg">
      <%= inline_svg('edit.svg', class: "h-4") %>
      <span class="ml-2">Edit</span>
    </li>
  <% end %>
</ul>

app/views/shared/sidebar/_left_sidebar.html.erb
<aside id="sidebar" class="sticky top-0 mr-28">
  <nav>
    <ul class="space-y-4 grid justify-items-start" data-controller="sidebar">
      <li class="mb-3 main-li"><%= inline_svg('icon.svg', class: "h-10") %></li>
      <%= link_to root_path do %>
        <li class="main-li"><%= inline_svg('home.svg', class: "h-10") %><p>Home</p></li>
      <% end %>
      <% if user_signed_in? %>
        <li class="flex items-center main-li" data-action="click->sidebar#toggle">
          <%= inline_svg('user.svg', class: "h-10") %>
          <div>
            <p class="text-base">Profile</p>
            <p class="text-sm text-gray-500">@<%= current_user.username %></p>
          </div>
          <%= render "shared/sidebar/dropdown" %>
        </li>
      <% end %>
    </ul>
  </nav>
</aside>

app/views/tweets/_input.html.erb
<div id="flash_messages">
  <%= render 'shared/flash_messages', tweet: @tweet %>
</div>
<%= form_with(model: tweet, class: "contents", data: { controller: "tweet", action: "turbo:submit-end->tweet#clearTextarea input->tweet#resize input->tweet#checkLength", local: false }) do |form| %>
  <div class="p-4 tweet-border">
    <%= form.text_area :body, data: { tweet_target: "textarea" }, class: "tweet-textarea", rows: "1", placeholder: "Hello, #{ user_signed_in? ? current_user.username : "Stranger" }. What's happening?" %>
    <div class="flex justify-end items-center text-center mt-4">
      <div data-tweet-target="count" class="tweet-char-count"></div>
      <% if user_signed_in? %>
        <%= form.submit "Tweet", class: "tweet-submit", data: { tweet_target: "submit" } %>
        <% else %>
        <%= link_to "Log in to create tweets", new_user_session_path, class: "tweet-submit" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<div id="<%= dom_id(tweet) %>" class="tweet-main-div flex items-start w-full relative" data-controller="dropdown" data-dropdown-hidden-class="hidden">
  <%= link_to users_profile_path(tweet.user_id), data: { turbo: false } do %>
      <%= inline_svg('user.svg', class: "h-11") %>
  <% end %>

  <div id="tweet" class="ml-2 flex-grow">
      <div class="flex justify-between w-full">
        <div class="flex items-center mb-1">
          <span class="text-gray-500 text-sm">@<%= tweet.user.username %> · <%= time_ago_in_words(tweet.created_at) %> </span>
        </div>
        <% if user_signed_in? && tweet.user_id == current_user.id %>
          <div class="flex items-start second-text">
            <span data-action="click->dropdown#toggle"><%= inline_svg('horizontal_dots.svg', class: "h-5") %> </span>
            <%= render partial: 'shared/dropdown/tweet', locals: { tweet: tweet } %>
          </div>
        <% end %>
      </div>

    <%= link_to tweet_path(tweet), data: { turbo: false } do %>
        <p class="tweet-body"><%= tweet.body %></p>
    <% end %>

    <div class="second-text flex justify-between mt-4">
      <%= inline_svg('like.svg', class: "h-5") %>
      <%= inline_svg('comment.svg', class: "h-5") %>
      <%= inline_svg('retweet.svg', class: "h-5") %>
      <div class="w-30"></div>
    </div>
  </div>
</div>

app/views/tweets/_tweet_input.html.erb
<%= form_with(model: tweet, class: "contents", data: { controller: "tweet", action: "turbo:submit-end->tweet#clearTextarea" }) do |form| %>
  <div class="p-4 tweet-border">
    <%= form.text_area :body, data: { tweet_target: "textarea" }, class: "tweet-textarea", rows: "1", placeholder: "Hello, #{ user_signed_in? ? current_user.username : "Stranger" }. What's happening?" %>
    <div class="flex justify-end items-center mt-4">

      <% if user_signed_in? %>
        <%= form.submit "Tweet", class: "tweet-submit" %>
        <% else %>
        <%= link_to "Log in to create tweets", new_user_session_path, class: "tweet-submit" %>
      <% end %>

    </div>
  </div>
<% end %>

app/views/tweets/create.turbo_stream.erb
<% if @tweet.persisted? %>
  <%= turbo_stream.prepend "tweets", partial: "tweets/tweet", locals: { tweet: @tweet } %>
<% end %>

<%= turbo_stream.append("flash_messages", partial: "shared/flash_messages") %>

app/views/tweets/destroy.turbo_stream.erb
<% if @tweet.destroyed? %>
  <%= turbo_stream.remove(@tweet) %>
<% end %>

<%= turbo_stream.append("flash_messages", partial: "shared/flash_messages") %>

app/views/tweets/edit.turbo_stream.erb
<%= turbo_stream.replace("modal", partial: "tweets/partials/edit", locals: { tweet: @tweet }) %>

app/views/tweets/new.html.erb
<%= render "tweets/partials/error", tweet: @tweet %>
<%= render "tweets/partials/form", tweet: @tweet %>

app/views/tweets/partials/_edit.html.erb
<div id="modal" data-controller="modal" data-dropdown-hidden-class="hidden" data-modal-target="container" class="modal-container hidden" >
  <div class="modal-overlay"></div>
  <div class="modal-content-wrapper">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title">
          Edit
        </h3>
        <button type="button" data-action="click->modal#close" class="modal-close-button">
          <%= inline_svg('close.svg') %>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'tweets/partials/form', tweet: tweet %>
      </div>
    </div>
  </div>
</div>

app/views/tweets/partials/_error.html.erb
<div id="tweet_error" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
  <ul>
    <% tweet.errors.each do |error| %>
      <li><%= error.full_message %></li>
    <% end %>
  </ul>
</div>

app/views/tweets/partials/_form.html.erb
<%= render 'shared/flash_messages', tweet: @tweet %>

<%= form_with(model: tweet, class: "contents", data: { controller: "tweet", action: "turbo:submit-end->tweet#clearTextarea input->tweet#resize input->tweet#checkLength", local: false }) do |form| %>
  <div class="p-4 tweet-border">
    <%= form.text_area :body, data: { tweet_target: "textarea" }, class: "tweet-textarea", rows: "1", placeholder: "Hello, #{ user_signed_in? ? current_user.username : "Stranger" }. What's happening?" %>
    <div class="flex justify-end items-center text-center mt-4">
      <div data-tweet-target="count" class="tweet-char-count"></div>
      <% if user_signed_in? %>
        <%= form.submit "Tweet", class: "tweet-submit", data: { tweet_target: "submit" } %>
        <% else %>
        <%= link_to "Log in to create tweets", new_user_session_path, class: "tweet-submit" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/tweets/show.html.erb
<% content_for :header_title do %>
  Tweet
<% end %>

<%= render 'tweets/tweet', tweet: @tweet %>

app/views/tweets/update.turbo_stream.erb
<% if @tweet.saved_changes? %>
  <%= turbo_stream.replace dom_id(@tweet) do %>
    <%= render partial: "tweets/tweet", locals: { tweet: @tweet } %>
  <% end %>
<% end %>

<%= turbo_stream.append("flash_messages", partial: "shared/flash_messages") %>

app/views/users/profiles/show.html.erb
<% content_for :header_title do %>

  <h3><%= @user.username %></h3>
  <p><%= @user.tweets.count %> tweets</p>
<% end %>
<%= render partial: 'tweets/tweet', collection: @tweets %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" class="bg-red-100 border-l-4 border-red-500 mt-3 p-4 rounded-md" data-turbo-cache="false">
    <h2 class="text-red-700 font-bold mb-2">
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
      %>
    </h2>
    <ul class="list-disc list-inside text-red-600">
      <% resource.errors.full_messages.each do |message| %>
        <li class="mb-1"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>